package com.bbva.rbvd.dto.lifeinsrc.utils;

public enum RBVDProperties {

    SIMULATION_LIFE_URI("simulation.rimac.life.uri"),
    SIMULATION_LIFE_RIMAC("simulationlife.rimac"),

    KEY_OF_INSRC_LIST_RESPONSES("dtoInsurance"),

    QUERY_GET_PRODUCT_INFORMATION("PISD.GET_PRODUCT_INFORMATION"),
    QUERY_GET_PRODUCT_MODALITIES_INFORMATION("PISD.GET_PRODUCT_MODALITIES_INFORMATION_LIFE"),
    QUERY_SELECT_INSURANCE_SIMULATION_ID("PISD.SELECT_INSURANCE_SIMULATION_ID_LIFE"),
    QUERY_INSERT_INSURANCE_SIMULATION("PISD.INSERT_INSURANCE_SIMULATION_LIFE"),
    QUERY_INSERT_INSRNC_SIMLT_PRD("PISD.INSERT_INSRNC_SIMLT_PRD_LIFE"),

    FIELD_OR_FILTER_INSURANCE_PRODUCT_ID("INSURANCE_PRODUCT_ID"),
    FIELD_SALE_CHANNEL_ID("SALE_CHANNEL_ID"),
    FIELD_MAIN_CONSIDERATION_IND_TYPE("MAIN_CONSIDERATION_IND_TYPE"),
    FIELD_INSURANCE_MODALITY_NAME("INSURANCE_MODALITY_NAME"),
    FIELD_SUGGESTED_MODALITY_IND_TYPE("SUGGESTED_MODALITY_IND_TYPE"),
    FIELD_OR_FILTER_INSURANCE_MODALITY_TYPE("INSURANCE_MODALITY_TYPE"),
    FIELD_PUBLICATION_ORDER_NUMBER("PUBLICATION_ORDER_NUMBER"),
    FIELD_INSURANCE_PRODUCT_DESC("INSURANCE_PRODUCT_DESC"),
    FIELD_INSURANCE_BUSINESS_NAME("INSURANCE_BUSINESS_NAME"),
    FIELD_INSURANCE_COMPANY_MODALITY_ID("INSURANCE_COMPANY_MODALITY_ID"),

    FIELD_INSURANCE_SIMULATION_ID("INSURANCE_SIMULATION_ID"),
    FIELD_INSRNC_COMPANY_SIMULATION_ID("INSRNC_COMPANY_SIMULATION_ID"),
    FIELD_CUSTOMER_ID("CUSTOMER_ID"),
    FIELD_CUSTOMER_SIMULATION_DATE("CUSTOMER_SIMULATION_DATE"),
    FIELD_CUST_SIMULATION_EXPIRED_DATE("CUST_SIMULATION_EXPIRED_DATE"),
    FIELD_BANK_FACTOR_TYPE("BANK_FACTOR_TYPE"),
    FIELD_BANK_FACTOR_AMOUNT("BANK_FACTOR_AMOUNT"),
    FIELD_BANK_FACTOR_PER("BANK_FACTOR_PER"),
    FIELD_SOURCE_BRANCH_ID("SOURCE_BRANCH_ID"),
    FIELD_CREATION_USER_ID("CREATION_USER_ID"),
    FIELD_USER_AUDIT_ID("USER_AUDIT_ID"),
    FIELD_CREATION_DATE("CREATION_DATE"),
    FIELD_PERSONAL_DOC_TYPE("PERSONAL_DOC_TYPE"),
    FIELD_PARTICIPANT_PERSONAL_ID("PARTICIPANT_PERSONAL_ID"),
    FIELD_INSURED_CUSTOMER_NAME("INSURED_CUSTOMER_NAME"),
    FIELD_CLIENT_LAST_NAME("CLIENT_LAST_NAME"),
    FIELD_CUSTOMER_SEGMENT_NAME("CUSTOMER_SEGMENT_NAME"),
    FIELD_CAMPAIGN_FACTOR_TYPE("CAMPAIGN_FACTOR_TYPE"),
    FIELD_CAMPAIGN_OFFER_1_AMOUNT("CAMPAIGN_OFFER_1_AMOUNT"),
    FIELD_CAMPAIGN_FACTOR_PER("CAMPAIGN_FACTOR_PER"),
    FILTER_INSURANCE_PRODUCT_TYPE("INSURANCE_PRODUCT_TYPE"),
    FIELD_Q_PISD_SIMULATION_ID0_NEXTVAL("NEXTVAL");

    private final String value;

    private RBVDProperties(String value) {
        this.value = value;
    }

    public String getValue() {
        return this.value;
    }
}
